### PR TITLE
fix: improve reliability of reconnecting to lotus after disconnect

### LINKED ISSUE #493: Visor losing connection to Lotus
### Describe the bug:

Visor is watching Lotus API and then gets disconnected and fails to reconnect

```
{"level":"debug","ts":"2021-04-27T18:01:07.667Z","logger":"chain","caller":"chain/watcher.go:88","msg":"tipset cache","height":"708001","tail_height":"707983","length":19}
{"level":"debug","ts":"2021-04-27T18:01:07.667Z","logger":"chain","caller":"chain/watcher.go:88","msg":"tipset cache","height":"708002","tail_height":"707983","length":20}
{"level":"debug","ts":"2021-04-27T18:01:07.667Z","logger":"chain","caller":"chain/watcher.go:88","msg":"tipset cache","height":"708001","tail_height":"707983","length":19}
{"level":"debug","ts":"2021-04-27T18:01:07.667Z","logger":"chain","caller":"chain/watcher.go:88","msg":"tipset cache","height":"708002","tail_height":"707983","length":20}
{"level":"debug","ts":"2021-04-27T18:01:07.727Z","logger":"chain","caller":"chain/indexer.go:366","msg":"task data persisted","height":707982,"task":"actorstatespower","time":7.36707321}
{"level":"debug","ts":"2021-04-27T18:01:07.727Z","logger":"chain","caller":"chain/indexer.go:370","msg":"tipset complete","height":707982,"total_time":7.367131808}
{"level":"info","ts":"2021-04-27T18:01:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:363","msg":"job exited cleanly","id":1,"name":"ChainHeadNotifier"}
{"level":"info","ts":"2021-04-27T18:01:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":1,"name":"ChainHeadNotifier","delay":60}
{"level":"error","ts":"2021-04-27T18:01:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:01:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:02:10.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:02:10.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:02:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:02:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:02:40.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:02:40.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:03:10.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:03:10.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:03:25.970Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":1,"name":"ChainHeadNotifier","error":"open lens: new full node rpc: dial tcp 172.20.125.53:1234: i/o >
{"level":"info","ts":"2021-04-27T18:03:25.970Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":1,"name":"ChainHeadNotifier","delay":60}
{"level":"error","ts":"2021-04-27T18:03:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:03:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:03:40.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:03:40.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:04:10.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:04:10.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:04:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:04:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:04:40.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:04:40.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:05:10.971Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":1,"name":"ChainHeadNotifier","error":"open lens: new full node rpc: dial tcp 172.20.125.53:1234: i/o >
{"level":"info","ts":"2021-04-27T18:05:10.971Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":1,"name":"ChainHeadNotifier","delay":60}
{"level":"error","ts":"2021-04-27T18:05:10.970Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:05:10.971Z","logger":"rpc","caller":"go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:667","msg":"Connection timeout","remote":"172.20.125.53:1234"}
{"level":"error","ts":"2021-04-27T18:05:40.970Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:05:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:06:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:06:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:07:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:07:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:08:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:08:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:09:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:09:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:10:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
{"level":"info","ts":"2021-04-27T18:10:40.971Z","logger":"schedule","caller":"schedule/scheduler.go:341","msg":"restarting job","id":2,"name":"Watcher","delay":60}
{"level":"error","ts":"2021-04-27T18:11:40.972Z","logger":"schedule","caller":"schedule/scheduler.go:355","msg":"job exited with failure","id":2,"name":"Watcher","error":"ChainNotify channel closed"}
```

### PR DESCRIPTION
**Pull request by iand**
This only relates to the `visor run watch` command. When the rpc connection to the api was lost (e.g. Lotus restarting) the chain notifier job would close the event channel by calling Cancel but did not recreate it when the job was restarted. This left the watcher job with a permanently closed channel. 

Fix by not closing the channel between job restarts, but reuse it and send head events once connection to Lotus has been re-established.

Requires #490 to be merged first

Fixes #493

### CODE REVIEW

File: schedule/scheduler.go [hunk 1]
```diff
@@ -21,7 +21,9 @@ var log = logging.Logger("schedule")
 
 type Job interface {
 	// Run starts running the task and blocks until the context is done or
-	// an error occurs.
+	// an error occurs. Run may be called again after an error or timeout to
+	// retry the job so implemententions must ensure that Run resets any
+	// necessary state.
 	Run(context.Context) error
```
Comment (frrist) [inline schedule/scheduler.go:27]: :+1:

File: commands/watch.go [hunk 2]
```diff
@@ -275,6 +275,7 @@ func (c *LotusChainNotifier) Run(ctx context.Context) error {
 		return xerrors.Errorf("open lens: %w", err)
 	}
 	defer closer()
+	log.Debugw("lens opened")
```
Comment (frrist) [inline commands/watch.go:278]: remnant from debugging?

File: commands/watch.go [hunk 3]
```diff
@@ -284,12 +285,10 @@ func (c *LotusChainNotifier) Run(ctx context.Context) error {
...
 		select {
 		case <-ctx.Done():
-			c.Cancel(ctx.Err())
-			return nil
+			return ctx.Err()
 		case headEvents, ok := <-hc:
 			if !ok {
-				c.Cancel(xerrors.Errorf("ChainNotify channel closed"))
-				return nil
+				return xerrors.Errorf("ChainNotify channel closed")
```
Comment (frrist) [inline commands/watch.go:291]: I believe these were the only usages of the `Cancel` method (line 255). Can we nix it if it's no longer being used?

**Review by frrist — APPROVED** [review]

File: commands/watch.go (hunk 2 above)
Comment (iand) [reply commands/watch.go:278]: it is, but harmless

File: commands/watch.go (hunk 3 above)
Comment (iand) [reply commands/watch.go:291]: Yeah maybe. I still think we may want to use it, but let's see how it turns out.
