### PR TITLE
fix(migrations): CREATE EXTENSION deadlocks inside migrations global lock

### LINKED ISSUE #179: Remove create extension from migration
### Describe the bug:
Migrations require a global lock which deadlocks when migration 1 is executed due to `create extension` statement which also requires a global lock. This statement should be removed from migrations and included in docs for manual application.

### Steps to Reproduce:
1. `./visor migrate --latest` on DB without timescaledb extension already enabled.

### PR DESCRIPTION
**Pull request by hsanjuan**
Instead, run this statement before obtaining the global lock for migrations.

Fixes #179 .

### CODE REVIEW

**Comment by hsanjuan** [comment]
#179 says that this should documented to be run manually, but I find that suboptimal vs just doing it for the user (doing it when it's not needed does not seem like a bad thing either). If I'm missing something, let me know.

File: storage/migrate.go [hunk 1]
```diff
@@ -89,6 +89,12 @@ func (d *Database) MigrateSchemaTo(ctx context.Context, target int) error {
 		return xerrors.Errorf("check migration sequence: %w", err)
 	}
 
+	// CREATE EXTENSION requires a global lock so it cannot be run inside
```
Comment (iand) [inline storage/migrate.go:92]: Let's do this after we have obtained the exclusive lock below. The lock is advisory and simply used to ensure that there is only one copy of visor using the database. It won't actually cause postgres to lock anything. I believe the restriction on the extension is that it can't be run inside a transaction.

File: storage/migrate.go [hunk 2]
```diff
@@ -94,6 +94,12 @@ func (d *Database) MigrateSchemaTo(ctx context.Context, target int) error {
 		return xerrors.Errorf("acquiring schema lock: %w", err)
 	}
 
+	// CREATE EXTENSION cannot run inside a transaction (as part of
```
Comment (iand) [inline storage/migrate.go:97]: We only need to do this when we are at schema version 0 (when dbVersion = 0)

Comment (hsanjuan) [reply storage/migrate.go:97]: Sorry for the delay, added that now.

**Review by iand — APPROVED** [review]
