### PR TITLE
fix(miner_info): track miner sector size

### LINKED ISSUE #523: Add sector size to miner_sector_infos
It is not there..

### PR DESCRIPTION
**Pull request by frrist**
- closes #523

I've tested the change locally and confirmed the migration and task wae.

### CODE REVIEW

File: tasks/actorstate/miner.go [hunk 1]
```diff
@@ -193,6 +193,10 @@ func ExtractMinerInfo(a ActorInfo, ec *MinerStateExtractionContext) (*minermodel
 		ConsensusFaultedElapsed: int64(newInfo.ConsensusFaultElapsed),
 		ControlAddresses:        newCtrlAddresses,
 		MultiAddresses:          newMultiAddrs,
+
+		// ShortString abbreviates the size as a human-scale number.
+		// This approximates (truncates) the size unless it is a power of 1024.
+		SectorSize: newInfo.SectorSize.ShortString(),
```
Comment (frrist) [inline tasks/actorstate/miner.go:199]: @hsanjuan what format would you prefer `sector_size` to be tracked with? Currently, this string will be one of: `1KiB`, `1MiB`, `1GiB`, `32GiB`, `64GiB`, etc. The other option would be an uint64: `1024`, `1048576`, `1073741824`, `34359738368`, `68719476736`, etc.

Comment (hsanjuan) [reply tasks/actorstate/miner.go:199]: uint64 please

Comment (frrist) [reply tasks/actorstate/miner.go]: ammended.

**Review by hsanjuan — APPROVED** [review]

**Review by iand — APPROVED** [review]
